[2024-03-20T22:12:17.470+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-20T22:10:00+00:00 [queued]>
[2024-03-20T22:12:17.623+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-20T22:10:00+00:00 [queued]>
[2024-03-20T22:12:17.629+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-20T22:12:17.814+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-20 22:10:00+00:00
[2024-03-20T22:12:17.864+0000] {standard_task_runner.py:60} INFO - Started process 703 to run task
[2024-03-20T22:12:17.966+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'sptoify_to_csv', 'scheduled__2024-03-20T22:10:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpq2_9d80u']
[2024-03-20T22:12:18.000+0000] {standard_task_runner.py:88} INFO - Job 168: Subtask sptoify_to_csv
[2024-03-20T22:41:51.998+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-20T22:10:00+00:00 [running]> on host ca1809388db1
[2024-03-20T22:41:53.157+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T22:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T22:10:00+00:00'
[2024-03-20T22:41:53.173+0000] {logging_mixin.py:188} INFO - The extract function has been executed and this is data in the next line
[2024-03-20T22:41:53.199+0000] {logging_mixin.py:188} INFO - Initiating the Endpoint...
[2024-03-20T22:41:56.695+0000] {logging_mixin.py:188} INFO - Extracting other available tracks
[2024-03-20T22:42:19.327+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-03-20T22:42:19.786+0000] {process_utils.py:131} INFO - Sending 15 to group 703. PIDs of all processes in the group: [703]
[2024-03-20T22:42:20.038+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 703
[2024-03-20T22:42:20.277+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-20T22:42:21.102+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 64, in Spotify_to_CSV
    top_tracks = sp.next(top_tracks['tracks'])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 347, in next
    return self._get(result["next"])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 272, in _internal_call
    results = response.json()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-20T22:42:21.700+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_s3_data_extraction_v1, task_id=sptoify_to_csv, execution_date=20240320T221000, start_date=20240320T221217, end_date=20240320T224221
[2024-03-20T22:42:23.002+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 168 for task sptoify_to_csv (Task received SIGTERM signal; 703)
[2024-03-20T22:42:23.923+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=703, status='terminated', exitcode=1, started='22:12:17') (703) terminated with exit code 1
