[2024-03-28T21:02:05.223+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extraction.sptoify_to_csv manual__2024-03-28T21:00:03.734741+00:00 [queued]>
[2024-03-28T21:02:05.232+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extraction.sptoify_to_csv manual__2024-03-28T21:00:03.734741+00:00 [queued]>
[2024-03-28T21:02:05.233+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 8
[2024-03-28T21:02:05.244+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-28 21:00:03.734741+00:00
[2024-03-28T21:02:05.250+0000] {standard_task_runner.py:60} INFO - Started process 988 to run task
[2024-03-28T21:02:05.253+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'billboard_to_spotify_to_s3_extraction', 'sptoify_to_csv', 'manual__2024-03-28T21:00:03.734741+00:00', '--job-id', '1467', '--raw', '--subdir', 'DAGS_FOLDER/billboard_to_spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmp4jmcl9zr']
[2024-03-28T21:02:05.256+0000] {standard_task_runner.py:88} INFO - Job 1467: Subtask sptoify_to_csv
[2024-03-28T21:02:05.300+0000] {task_command.py:423} INFO - Running <TaskInstance: billboard_to_spotify_to_s3_extraction.sptoify_to_csv manual__2024-03-28T21:00:03.734741+00:00 [running]> on host bc244bd8b198
[2024-03-28T21:02:05.366+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='billboard_to_spotify_to_s3_extraction' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-28T21:00:03.734741+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-28T21:00:03.734741+00:00'
[2024-03-28T21:02:05.376+0000] {logging_mixin.py:188} INFO - GOT THE TOP ARTISTS DAT FROM XCOM
[2024-03-28T21:02:05.376+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS BIO DATA
[2024-03-28T21:02:05.984+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS ALBUMS DATA
[2024-03-28T21:02:06.504+0000] {logging_mixin.py:188} INFO - Taylor Swift has appeared on a total of 385 albums
[2024-03-28T21:02:06.505+0000] {logging_mixin.py:188} INFO -  Now stagging the albums ...
[2024-03-28T21:02:13.888+0000] {logging_mixin.py:188} INFO -  Taylor Swift albums stagged ... 
[2024-03-28T21:02:13.889+0000] {logging_mixin.py:188} INFO -  transforming Taylor Swift albums data ... 
[2024-03-28T21:02:13.890+0000] {logging_mixin.py:188} INFO - GETTING ALBUMS TRACKS DATA
[2024-03-28T21:02:14.179+0000] {logging_mixin.py:188} INFO -  Now stagging the tracks ...
[2024-03-28T21:02:14.180+0000] {logging_mixin.py:188} INFO -  1989 (Taylor's Version) [Deluxe] tracks stagged ... 
[2024-03-28T21:02:14.181+0000] {logging_mixin.py:188} INFO -  transforming 1989 (Taylor's Version) [Deluxe] tracks data ... 
[2024-03-28T21:02:16.722+0000] {client.py:302} ERROR - Max Retries reached
[2024-03-28T21:02:16.723+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 894, in urlopen
    return self.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 884, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 266, in _internal_call
    response = self._session.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.spotify.com', port=443): Max retries exceeded with url: /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt (Caused by ResponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/billboard_to_spotify_to_csvs_to_s3.py", line 155, in Spotify_to_CSV
    track_features = sp.audio_features(track['uri'])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1734, in audio_features
    results = self._get("audio-features/?ids=" + trackid)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 307, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 429, code:-1 - /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt:
 Max Retries, reason: too many 429 error responses
[2024-03-28T21:02:16.734+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=billboard_to_spotify_to_s3_extraction, task_id=sptoify_to_csv, execution_date=20240328T210003, start_date=20240328T210205, end_date=20240328T210216
[2024-03-28T21:02:16.746+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1467 for task sptoify_to_csv (http status: 429, code:-1 - /v1/audio-features/?ids=4WUepByoeqcedHoYhSNHRt:
 Max Retries, reason: too many 429 error responses; 988)
[2024-03-28T21:02:16.766+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T21:02:16.786+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
