[2024-03-22T10:22:19.275+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T05:08:00+00:00 [queued]>
[2024-03-22T10:22:19.298+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T05:08:00+00:00 [queued]>
[2024-03-22T10:22:19.300+0000] {taskinstance.py:2193} INFO - Starting attempt 7 of 12
[2024-03-22T10:22:19.334+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-21 05:08:00+00:00
[2024-03-22T10:22:19.348+0000] {standard_task_runner.py:60} INFO - Started process 5717 to run task
[2024-03-22T10:22:19.361+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'sptoify_to_csv', 'scheduled__2024-03-21T05:08:00+00:00', '--job-id', '1197', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpakmx8mjc']
[2024-03-22T10:22:19.370+0000] {standard_task_runner.py:88} INFO - Job 1197: Subtask sptoify_to_csv
[2024-03-22T10:22:19.494+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T05:08:00+00:00 [running]> on host ca1809388db1
[2024-03-22T10:22:19.676+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T05:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T05:08:00+00:00'
[2024-03-22T10:22:19.679+0000] {logging_mixin.py:188} INFO - The extract function has been executed and this is data in the next line
[2024-03-22T10:22:19.680+0000] {logging_mixin.py:188} INFO - Initiating the Endpoint...
[2024-03-22T10:22:21.349+0000] {logging_mixin.py:188} INFO - Extracting other available tracks
[2024-03-22T10:22:32.782+0000] {logging_mixin.py:188} INFO - Adding the values of index 0 into the appropriate Keys...
[2024-03-22T10:22:41.524+0000] {logging_mixin.py:188} INFO - Adding the values of index 1 into the appropriate Keys...
[2024-03-22T10:22:42.375+0000] {logging_mixin.py:188} INFO - Adding the values of index 2 into the appropriate Keys...
[2024-03-22T10:22:43.218+0000] {logging_mixin.py:188} INFO - Adding the values of index 3 into the appropriate Keys...
[2024-03-22T10:22:44.140+0000] {logging_mixin.py:188} INFO - Adding the values of index 4 into the appropriate Keys...
[2024-03-22T18:44:59.970+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
[2024-03-22T18:45:02.270+0000] {process_utils.py:131} INFO - Sending 15 to group 5717. PIDs of all processes in the group: [5717]
[2024-03-22T18:45:02.311+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 5717
[2024-03-22T18:45:02.933+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-22T18:45:03.975+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 110, in Spotify_to_CSV
    data['Artist_Genres'].append(sp.artist(track['artists'][0]['id'])['genres'])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 392, in artist
    return self._get("artists/" + trid)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 266, in _internal_call
    response = self._session.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 892, in urlopen
    retries.sleep(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 428, in sleep
    slept = self.sleep_for_retry(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 407, in sleep_for_retry
    time.sleep(retry_after)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-22T18:45:04.179+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_s3_data_extraction_v1, task_id=sptoify_to_csv, execution_date=20240321T050800, start_date=20240322T102219, end_date=20240322T184504
[2024-03-22T18:45:04.740+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1197 for task sptoify_to_csv (Task received SIGTERM signal; 5717)
[2024-03-22T18:45:05.477+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5717, status='terminated', exitcode=1, started='10:22:18') (5717) terminated with exit code 1
