[2024-03-21T00:07:05.181+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T00:06:00+00:00 [queued]>
[2024-03-21T00:07:05.201+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T00:06:00+00:00 [queued]>
[2024-03-21T00:07:05.202+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-21T00:07:05.256+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-21 00:06:00+00:00
[2024-03-21T00:07:05.275+0000] {standard_task_runner.py:60} INFO - Started process 1038 to run task
[2024-03-21T00:07:05.285+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'sptoify_to_csv', 'scheduled__2024-03-21T00:06:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpdsf2p9n_']
[2024-03-21T00:07:05.295+0000] {standard_task_runner.py:88} INFO - Job 227: Subtask sptoify_to_csv
[2024-03-21T00:07:05.445+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T00:06:00+00:00 [running]> on host ca1809388db1
[2024-03-21T00:07:05.656+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T00:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T00:06:00+00:00'
[2024-03-21T00:07:05.661+0000] {logging_mixin.py:188} INFO - The extract function has been executed and this is data in the next line
[2024-03-21T00:07:05.663+0000] {logging_mixin.py:188} INFO - Initiating the Endpoint...
[2024-03-21T00:12:19.700+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=False, redirect=None, status=3)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f18ac8eb7f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /v1/search?q=year%3A2024&limit=50&offset=0&type=track&market=US
[2024-03-21T00:12:20.973+0000] {logging_mixin.py:188} INFO - Extracting other available tracks
[2024-03-21T00:12:31.380+0000] {logging_mixin.py:188} INFO - Adding the values of index 0 into the appropriate Keys...
[2024-03-21T00:12:32.698+0000] {logging_mixin.py:188} INFO - Adding the values of index 1 into the appropriate Keys...
[2024-03-21T00:12:34.046+0000] {logging_mixin.py:188} INFO - Adding the values of index 2 into the appropriate Keys...
[2024-03-21T00:12:35.581+0000] {logging_mixin.py:188} INFO - Adding the values of index 3 into the appropriate Keys...
[2024-03-21T00:12:37.017+0000] {logging_mixin.py:188} INFO - Adding the values of index 4 into the appropriate Keys...
[2024-03-21T00:12:38.917+0000] {logging_mixin.py:188} INFO - Adding the values of index 5 into the appropriate Keys...
[2024-03-21T00:12:40.846+0000] {logging_mixin.py:188} INFO - Adding the values of index 6 into the appropriate Keys...
[2024-03-21T00:12:42.765+0000] {logging_mixin.py:188} INFO - Adding the values of index 7 into the appropriate Keys...
[2024-03-21T00:12:44.252+0000] {logging_mixin.py:188} INFO - Adding the values of index 8 into the appropriate Keys...
[2024-03-21T00:12:46.388+0000] {logging_mixin.py:188} INFO - Adding the values of index 9 into the appropriate Keys...
[2024-03-21T00:12:47.816+0000] {logging_mixin.py:188} INFO - Done Extracting...
[2024-03-21T00:12:48.099+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-21T00:12:48.412+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=spotify_to_s3_data_extraction_v1, task_id=sptoify_to_csv, execution_date=20240321T000600, start_date=20240321T000705, end_date=20240321T001248
[2024-03-21T00:12:48.958+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-21T00:12:50.193+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
