[2024-04-01T01:15:26.272+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-03-31T00:00:00+00:00 [queued]>
[2024-04-01T01:15:26.296+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-03-31T00:00:00+00:00 [queued]>
[2024-04-01T01:15:26.297+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-04-01T01:15:26.335+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-31 00:00:00+00:00
[2024-04-01T01:15:26.349+0000] {standard_task_runner.py:60} INFO - Started process 14168 to run task
[2024-04-01T01:15:26.356+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'billboard_to_spotify_to_s3_extractionV1', 'sptoify_to_csv', 'scheduled__2024-03-31T00:00:00+00:00', '--job-id', '1525', '--raw', '--subdir', 'DAGS_FOLDER/billboard_to_spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpb0e7251k']
[2024-04-01T01:15:26.362+0000] {standard_task_runner.py:88} INFO - Job 1525: Subtask sptoify_to_csv
[2024-04-01T01:15:26.465+0000] {task_command.py:423} INFO - Running <TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-03-31T00:00:00+00:00 [running]> on host bdb7303f046f
[2024-04-01T01:15:26.651+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='billboard_to_spotify_to_s3_extractionV1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-31T00:00:00+00:00'
[2024-04-01T01:15:26.677+0000] {logging_mixin.py:188} INFO - GOT THE TOP ARTISTS DAT FROM XCOM
[2024-04-01T01:15:26.679+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS BIO DATA
[2024-04-01T01:15:28.568+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS ALBUMS DATA
[2024-04-01T01:15:28.916+0000] {logging_mixin.py:188} INFO - Taylor Swift has appeared on a total of 385 albums
[2024-04-01T01:15:28.917+0000] {logging_mixin.py:188} INFO -  Now stagging the albums ...
[2024-04-01T01:15:40.429+0000] {logging_mixin.py:188} INFO -  Taylor Swift albums stagged ... 
[2024-04-01T01:15:40.452+0000] {logging_mixin.py:188} INFO -  transforming Taylor Swift albums data ... 
[2024-04-01T01:15:40.460+0000] {logging_mixin.py:188} INFO - GETTING ALBUMS TRACKS DATA
[2024-04-01T01:15:44.630+0000] {logging_mixin.py:188} INFO -  Now stagging the tracks ...
[2024-04-01T01:15:44.644+0000] {logging_mixin.py:188} INFO -  1989 (Taylor's Version) [Deluxe] tracks stagged ... 
[2024-04-01T01:15:44.653+0000] {logging_mixin.py:188} INFO -  transforming 1989 (Taylor's Version) [Deluxe] tracks data ... 
[2024-04-01T01:15:47.126+0000] {logging_mixin.py:188} INFO - GETTING ALBUMS TRACKS DATA
[2024-04-01T01:15:47.445+0000] {logging_mixin.py:188} INFO -  Now stagging the tracks ...
[2024-04-01T01:15:47.451+0000] {logging_mixin.py:188} INFO -  1989 (Taylor's Version) tracks stagged ... 
[2024-04-01T01:15:47.458+0000] {logging_mixin.py:188} INFO -  transforming 1989 (Taylor's Version) tracks data ... 
[2024-04-01T01:30:54.283+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 469, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/billboard_to_spotify_to_csvs_to_s3.py", line 156, in Spotify_to_CSV
    track_features = sp.audio_features(track['uri'])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 1734, in audio_features
    results = self._get("audio-features/?ids=" + trackid)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 266, in _internal_call
    response = self._session.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)
[2024-04-01T01:30:54.616+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=billboard_to_spotify_to_s3_extractionV1, task_id=sptoify_to_csv, execution_date=20240331T000000, start_date=20240401T011526, end_date=20240401T013054
[2024-04-01T01:30:56.041+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1525 for task sptoify_to_csv (HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5); 14168)
[2024-04-01T01:30:56.086+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T01:30:56.239+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
