[2024-03-24T09:50:01.550+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_VV_Error-Resolve_x64.upload_csv_to_s3 manual__2024-03-24T08:13:45.471205+00:00 [queued]>
[2024-03-24T09:50:01.565+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_VV_Error-Resolve_x64.upload_csv_to_s3 manual__2024-03-24T08:13:45.471205+00:00 [queued]>
[2024-03-24T09:50:01.567+0000] {taskinstance.py:2193} INFO - Starting attempt 8 of 12
[2024-03-24T09:50:01.588+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): upload_csv_to_s3> on 2024-03-24 08:13:45.471205+00:00
[2024-03-24T09:50:01.598+0000] {standard_task_runner.py:60} INFO - Started process 3937 to run task
[2024-03-24T09:50:01.604+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_VV_Error-Resolve_x64', 'upload_csv_to_s3', 'manual__2024-03-24T08:13:45.471205+00:00', '--job-id', '1399', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpo59470wr']
[2024-03-24T09:50:01.609+0000] {standard_task_runner.py:88} INFO - Job 1399: Subtask upload_csv_to_s3
[2024-03-24T09:50:01.711+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_VV_Error-Resolve_x64.upload_csv_to_s3 manual__2024-03-24T08:13:45.471205+00:00 [running]> on host bc244bd8b198
[2024-03-24T09:50:01.835+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_VV_Error-Resolve_x64' AIRFLOW_CTX_TASK_ID='upload_csv_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:13:45.471205+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:13:45.471205+00:00'
[2024-03-24T09:50:01.837+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 150, in upload_csv_to_s3
    print(csv_filenames + 'are the files to be uploaded')
TypeError: can only concatenate list (not "str") to list
[2024-03-24T09:50:01.851+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_s3_data_extraction_VV_Error-Resolve_x64, task_id=upload_csv_to_s3, execution_date=20240324T081345, start_date=20240324T095001, end_date=20240324T095001
[2024-03-24T09:50:01.870+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1399 for task upload_csv_to_s3 (can only concatenate list (not "str") to list; 3937)
[2024-03-24T09:50:01.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T09:50:01.930+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
