[2024-04-14T02:28:09.735+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T02:28:09.749+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T02:28:09.750+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-04-14T02:28:09.771+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-04-13 00:00:00+00:00
[2024-04-14T02:28:09.785+0000] {standard_task_runner.py:60} INFO - Started process 13370 to run task
[2024-04-14T02:28:09.791+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'billboard_to_spotify_to_s3_extractionV1', 'sptoify_to_csv', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '1676', '--raw', '--subdir', 'DAGS_FOLDER/billboard_to_spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpf0xp1wg3']
[2024-04-14T02:28:09.796+0000] {standard_task_runner.py:88} INFO - Job 1676: Subtask sptoify_to_csv
[2024-04-14T02:28:09.879+0000] {task_command.py:423} INFO - Running <TaskInstance: billboard_to_spotify_to_s3_extractionV1.sptoify_to_csv scheduled__2024-04-13T00:00:00+00:00 [running]> on host 66d8d046c9ac
[2024-04-14T02:28:10.004+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='billboard_to_spotify_to_s3_extractionV1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T00:00:00+00:00'
[2024-04-14T02:28:10.021+0000] {logging_mixin.py:188} INFO - GOT THE TOP ARTISTS DAT FROM XCOM
[2024-04-14T02:28:10.022+0000] {logging_mixin.py:188} INFO - GETTING ARTISTS BIO DATA
[2024-04-14T02:28:10.498+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 265, in _request_access_token
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/billboard_to_spotify_to_csvs_to_s3.py", line 93, in Spotify_to_CSV
    s_artist = sp.search(q=artist, type='artist', limit=1)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 587, in search
    return self._get(
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 247, in _internal_call
    headers = self._auth_headers()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 238, in _auth_headers
    token = self.auth_manager.get_access_token(as_dict=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 238, in get_access_token
    token_info = self._request_access_token()
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 269, in _request_access_token
    self._handle_oauth_error(http_error)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/oauth2.py", line 146, in _handle_oauth_error
    raise SpotifyOauthError(
spotipy.oauth2.SpotifyOauthError: error: invalid_client, error_description: Failed to get client
[2024-04-14T02:28:10.515+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=billboard_to_spotify_to_s3_extractionV1, task_id=sptoify_to_csv, execution_date=20240413T000000, start_date=20240414T022809, end_date=20240414T022810
[2024-04-14T02:28:10.535+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1676 for task sptoify_to_csv (error: invalid_client, error_description: Failed to get client; 13370)
[2024-04-14T02:28:10.574+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-14T02:28:10.607+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
